extends@: default

form:
  fields:
    tabs:
      fields:
        advanced:
          fields:
            overrides:
              fields:
                header.book:
                  type: toggle
                  toggleable: true
                  label: Book root
                  description: "Turn this page in a book's entry point with a
                  sidebar menu for all its sub-pages."
                  highlight: 0
                  options:
                    1: PLUGIN_ADMIN.ENABLED
                    0: PLUGIN_ADMIN.DISABLED
                  validate:
                    type: bool
                header.clickable:
                  type: toggle
                  toggleable: true
                  label: Clickable
                  description: "Disable this item in the menu."
                  highlight: 1
                  options:
                    1: PLUGIN_ADMIN.ENABLED
                    0: PLUGIN_ADMIN.DISABLED
                  validate:
                    type: bool
            columns:
              fields:
                column1:
                   fields:
                     header.body_classes:
                       markdown: true
                       description: 'Available classes in Afj Theme (space
                       separated):<br />`header-fixed`, `header-animated`,
                       `header-dark`, `header-transparent`, `sticky-footer`'
        content:
          fields:
            header.sidebar_files:
              name: side_files
              label: File(s) in sidebar
              type: list
              style: vertical
              fields:
                .section_name:
                  label: Section name
                  type: text
                  toggleable: true
                .files:
                  name: files
                  label: File(s)
                  type: list
                  style: vertical
                  fields:
                    .name:
                      label: Name
                      type: text
                    .file:
                      label: File
                      type: pagemediaselect
                      multiple: false
                      # validate:
                      #     type: array #without it nothing happen on save...
