superadmin:
  access:
    site:
      login: true
    admin:
      login: true
      super: true
      cache: true
      configuration: true
      pages: true
      maintenance: true
      statistics: true
      plugins: true
      themes: true
      tools: true
      users: true
      flex-objects: true
  readableName: Jonglus
  enabled: true
content_manager:
  access:
    admin:
      login: true
      super: false
      configuration: false
      pages: true
      statistics: true
      plugins: false
      themes: false
      tools: false
      users: true
      flex-objects: false
  readableName: 'Editeur de contenu'
  enabled: true
