git-sync:
  repository: 'https://github.com/team-afj/grav-user.git'
  folders:
    - pages
    - config
    - plugins
    - themes
    - images
  git:
    ignore: "security.yaml\ngit-sync.yaml\nversions.yaml\n\n!.gitignore\n.gitkeep"
    author: gituser
    message: '(Grav GitSync) Automatic Commit'
    name: GitSync
    email: git-sync@trilby.media
    bin: git
    private_key: null
  SyncNotice: null
  sync:
    on_save: true
    on_delete: true
    on_media: true
    cron_enable: false
    cron_at: '0 12,23 * * *'
  local_repository: null
  no_user: '0'
  logging: false
  branch: main
  webhook_enabled: '1'
  remote:
    name: origin
    branch: main
